اضافه کردن راهنمای بیلد از سورس کد
kahroba-lang/kahroba pull request #7
Opened 2022-08-31 20:01 UTC by bistcuite

2022-09-01 06:43 UTC, kahroba-lang requested changes

2022-09-01 06:43 UTC, kahroba-lang commented on 2_parser.go
> -این استراکت برای نگهداری طول یک آرایه یا مپ استفاده میشود
این توضیح مربوط به Len حذف شده

2022-09-01 06:43 UTC, kahroba-lang commented on 2_parser.go
> +	A Node
لطفا یک اسم معنی دار تر انتخاب کن . همون Prompt عالیه

2022-09-02 08:25 UTC, bistcuite commented
تغییرات درخواست شده اعمال شد

2022-09-02 13:11 UTC, merged