add (.khb) file extension in README
kahroba-lang/kahroba pull request #9
Opened 2022-09-03 15:45 UTC by amirmalekian

2022-09-03 21:05 UTC, kahroba-lang requested changes

2022-09-03 21:05 UTC, kahroba-lang commented on readme.md
> +برای اجرای برنامه های به زبان کهربا لازم است برنامه خود را در فایلی با پسوند .kahroba یا .khb بسازید (مانند main.kahroba یا main.khb) و از خط فرمان برنامه را اجرا کنید:
بنظرم krb پسوند بهتریه تا khb چون ترکیب kh "خ" خونده میشه

2022-09-04 05:33 UTC, amirmalekian reviewed
ویرایش پسوند .khb به .krb

2022-09-04 05:35 UTC, amirmalekian commented on readme.md
> +برای اجرای برنامه های به زبان کهربا لازم است برنامه خود را در فایلی با پسوند .kahroba یا .krb بسازید (مانند main.kahroba یا main.krb) و از خط فرمان برنامه را اجرا کنید:
ویرایش پسوند .khb به .krb

2022-09-04 05:37 UTC, amirmalekian commented on readme.md
> +برای اجرای برنامه های به زبان کهربا لازم است برنامه خود را در فایلی با پسوند .kahroba یا .khb بسازید (مانند main.kahroba یا main.khb) و از خط فرمان برنامه را اجرا کنید:
بله درسته
باهاتون موافقم

2022-09-04 12:28 UTC, merged